// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/module

// Package module is here to define any struct necessary to build a plugin compatible with Perses.
// The definition of a plugin is different to the one you can find in the dashboard definition.
// The plugin definition in the dashboard is more about the configuration of a plugin, while the one in the module is more about the definition of a plugin.
// The module definition is stricter and is used to validate the plugin before it is loaded into Perses.
package module

import "github.com/perses/spec/cue/common"

#Kind: string // #enumKind

#enumKind:
	#KindVariable |
	#KindDatasource |
	#KindPanel |
	#KindTimeSeriesQuery |
	#KindTraceQuery |
	#KindProfileQuery |
	#KindLogQuery |
	#KindQuery |
	#KindAlertsQuery |
	#KindSilencesQuery |
	#KindExplore |
	#KindAnnotation

#KindVariable:        #Kind & "Variable"
#KindDatasource:      #Kind & "Datasource"
#KindPanel:           #Kind & "Panel"
#KindTimeSeriesQuery: #Kind & "TimeSeriesQuery"
#KindTraceQuery:      #Kind & "TraceQuery"
#KindProfileQuery:    #Kind & "ProfileQuery"
#KindLogQuery:        #Kind & "LogQuery"
#KindQuery:           #Kind & "Query"
#KindAlertsQuery:     #Kind & "AlertsQuery"
#KindSilencesQuery:   #Kind & "SilencesQuery"
#KindExplore:         #Kind & "Explore"
#KindAnnotation:      #Kind & "Annotation"

#PluginSpec: {
	display?: null | common.#Display @go(Display,*common.Display)
	name:     string                 @go(Name)
}

#Plugin: _

#Status: {
	isLoaded: bool   @go(IsLoaded)
	inDev:    bool   @go(InDev)
	error?:   string @go(Error)
}

#Module: _

#Metadata: {
	name:     string @go(Name)
	version:  string @go(Version)
	registry: string @go(Registry)
}
