// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/module

// Package module is here to define any struct necessary to build a plugin compatible with Perses.
// The definition of a plugin is different to the one you can find in the dashboard definition.
// The plugin definition in the dashboard is more about the configuration of a plugin, while the one in the module is more about the definition of a plugin.
// The module definition is stricter and is used to validate the plugin before it is loaded into Perses.
package module

import "github.com/perses/spec/cue/common"

#PluginSpec: {
	display?: null | common.#Display @go(Display,*common.Display)
	name:     string                 @go(Name)
}

#Plugin: _

#Status: {
	isLoaded: bool   @go(IsLoaded)
	inDev:    bool   @go(InDev)
	error?:   string @go(Error)
}

#Module: _

#Metadata: {
	name:     string @go(Name)
	version:  string @go(Version)
	registry: string @go(Registry)
}
