// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/datasource/proxy

package proxy

// Proxy is the generic struct of the proxy definition
#Proxy: {
	kind: string @go(Kind)
	spec: _      @go(Spec,T)
}
