// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/datasource

package datasource

import (
	"github.com/perses/spec/cue/common"
	plugin_9 "github.com/perses/spec/cue/plugin"
)

#Spec: {
	display?: null | common.#Display @go(Display,*common.Display)
	default:  bool                   @go(Default)

	// Plugin will contain the datasource configuration.
	// The data typed is available in Cue.
	plugin: plugin_9.#Plugin @go(Plugin)
}

// HTTPDatasourceSpec is the struct that can be used to define an HTTP Datasource plugin.
// To be used when implementing a plugin, and you want to provide the associated go-sdk.
// This struct is just here to avoid developer to redefine the same struct in their own plugin implementation,
// because most of the time developers do not need more field than the two proposed.
// If you need more, define your own struct and use it in your plugin implementation.
#HTTPDatasourceSpec: _

// SQLDatasourceSpec is the struct that can be used to define an SQL Datasource plugin.
// To be used when implementing a plugin, and you want to provide the associated go-sdk.
// This struct is just here to avoid developer to redefine the same struct in their own plugin implementation,
// because most of the time developers do not need more field than the two proposed.
// If you need more, define your own struct and use it in your plugin implementation.
#SQLDatasourceSpec: _
