// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/datasource

package datasource

import "github.com/perses/spec/cue/common"

#Spec: {
	display?: null | common.#Display @go(Display,*common.Display)
	default:  bool                   @go(Default)

	// Plugin will contain the datasource configuration.
	// The data typed is available in Cue.
	plugin: common.#Plugin @go(Plugin)
}
