// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/plugin

package plugin

#LatestVersion:   "latest"
#DefaultRegistry: "perses.dev"

#Metadata: {
	// Version is optional. If not provided, it means the latest version available in the Perses instance.
	// Version needs to follow the semantic versioning format (e.g., "1.0.0" or "v1.0.0")
	version?: string @go(Version)

	// Registry is optional. If not provided, it means the default registry is: "perses.dev".
	registry?: string @go(Registry)
}

#Plugin: _
