// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/common

package common

// +kubebuilder:validation:Schemaless
// +kubebuilder:validation:Type=string
// +kubebuilder:validation:Format=uri
#URL: _
