// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/dashboard

package dashboard

import plugin_9 "github.com/perses/spec/cue/plugin"

#Link: {
	name?:            string @go(Name)
	url:              string @go(URL)
	tooltip?:         string @go(Tooltip)
	renderVariables?: bool   @go(RenderVariables)
	targetBlank?:     bool   @go(TargetBlank)
}

#PanelDisplay: {
	name?:        string @go(Name)
	description?: string @go(Description)
}

#PanelSpec: {
	display?: null | #PanelDisplay @go(Display,*PanelDisplay)
	plugin:   plugin_9.#Plugin     @go(Plugin)
	queries?: [...#Query] @go(Queries,[]Query)
	links?: [...#Link] @go(Links,[]Link)
	annotations?: [...#AnnotationSpec] @go(Annotations,[]AnnotationSpec)
}

#Panel: {
	kind: string     @go(Kind)
	spec: #PanelSpec @go(Spec)
}

#Query: {
	kind: string     @go(Kind)
	spec: #QuerySpec @go(Spec)
}

#QuerySpec: {
	name?:  string           @go(Name)
	plugin: plugin_9.#Plugin @go(Plugin)
}

#Spec: _
