// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/dashboard

package dashboard

import plugin_9 "github.com/perses/spec/cue/plugin"

#Link: {
	name?:            string @go(Name)
	url:              string @go(URL)
	tooltip?:         string @go(Tooltip)
	renderVariables?: bool   @go(RenderVariables)
	targetBlank?:     bool   @go(TargetBlank)
}

#PanelDisplay: {
	name?:        string @go(Name)
	description?: string @go(Description)
}

#PanelSpec: {
	// Preserve unknown fields so plugins and downstream tooling can attach display-level
	// metadata without it being pruned at admission. The declared fields above stay validated;
	// Schemaless is intentionally not used, as that would drop their schema entirely.
	// +kubebuilder:pruning:PreserveUnknownFields
	display?: null | #PanelDisplay @go(Display,*PanelDisplay)
	plugin:   plugin_9.#Plugin     @go(Plugin)
	queries?: [...#Query] @go(Queries,[]Query)
	links?: [...#Link] @go(Links,[]Link)
}

#Panel: {
	kind: string @go(Kind)

	// Preserve unknown fields so plugins and downstream tooling can attach panel-level
	// metadata without it being pruned at admission. The declared fields stay validated;
	// Schemaless is intentionally not used, as that would drop their schema entirely.
	// +kubebuilder:pruning:PreserveUnknownFields
	spec: #PanelSpec @go(Spec)
}

#Query: {
	kind: string     @go(Kind)
	spec: #QuerySpec @go(Spec)
}

#QuerySpec: {
	name?:  string           @go(Name)
	plugin: plugin_9.#Plugin @go(Plugin)
}

#Spec: _
