// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/datasource/proxy/sql

package sql

import (
	"github.com/perses/spec/cue/common"
	"github.com/perses/spec/cue/datasource/proxy"
)

// Driver the SQL driver to use
#Driver: string // #enumDriver

#enumDriver:
	#DriverMySQL |
	#DriverMariaDB |
	#DriverPostgreSQL

#DriverMySQL:      #Driver & "mysql"
#DriverMariaDB:    #Driver & "mariadb"
#DriverPostgreSQL: #Driver & "postgres"

// SSLMode postgres ssl modes
#SSLMode: string // #enumSSLMode

#enumSSLMode:
	#SSLModeDisable |
	#SSLModeAllow |
	#SSLModePreferable |
	#SSLModeRequire |
	#SSLModeVerifyFull |
	#SSLModeVerifyCA

#SSLModeDisable:    #SSLMode & "disable"
#SSLModeAllow:      #SSLMode & "allow"
#SSLModePreferable: #SSLMode & "prefer"
#SSLModeRequire:    #SSLMode & "require"
#SSLModeVerifyFull: #SSLMode & "verify-full"
#SSLModeVerifyCA:   #SSLMode & "verify-ca"

#MySQLConfig: {
	params?: {[string]: string} @go(Params,map[string]string)
	maxAllowedPacket?: int                    @go(MaxAllowedPacket)
	timeout?:          common.#DurationString @go(Timeout)
	readTimeout?:      common.#DurationString @go(ReadTimeout)
	writeTimeout?:     common.#DurationString @go(WriteTimeout)
}

#PostgresConfig: _

#Config: _

// Proxy is the SQL proxy definition proposed in Perses.
// In case you are defining a datasource that will work with the Perses backend, then you will need to use this definition.
#Proxy: proxy.#Proxy

#ProxyKindName: "sqlproxy"
