// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/perses/spec/go/datasource/proxy/http

package http

import "github.com/perses/spec/cue/datasource/proxy"

#AllowedEndpoint: _

#Config: _

// Proxy is the HTTP proxy definition proposed in Perses.
// In case you are defining a datasource that will work with the Perses backend, then you will need to use this definition.
#Proxy: proxy.#Proxy

#ProxyKindName: "httpproxy"
